# Generated by Django 6.0 on 2025-12-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='proof_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='proof_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='proof_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
