# Generated by Django 6.0 on 2025-12-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_stripe_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='auto_bridge',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='proof_data',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='proof_mime',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='proof_name',
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('has_prerequisite', models.BooleanField(default=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('proof_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_data', models.BinaryField(blank=True, null=True)),
                ('enrollment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='core.registration')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('registration', 'course_name')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.studentcourseenrollment'),
        ),
    ]
