# Generated by Django 4.2.27 on 2026-01-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enhance_otp_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentotp',
            new_name='core_paymen_payment_bf8f8c_idx',
            old_name='core_paymen_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentotp',
            new_name='core_paymen_expires_708ed3_idx',
            old_name='core_paymen_expires_idx',
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentotp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
