# Generated by Django 6.0 on 2026-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_delete_courseprice_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_password',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
