# Generated by Django 4.2.27 on 2026-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_registration_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('session_for', models.CharField(max_length=30)),
                ('session_type', models.CharField(max_length=30)),
                ('mode', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('participants', models.PositiveIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='referral_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('social_media', 'Social Media (Facebook, Instagram)'), ('friend_family', 'Friend / Family Recommendation'), ('website_blog', 'Website / Blog'), ('webinar_workshop', 'Webinar / Workshop'), ('school_university', 'School / University'), ('other', 'Other (Please specify)')], default='', max_length=32),
        ),
    ]
